/* eslint-disable @typescript-eslint/no-explicit-any */
import { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
    ArrowLeft,
    DollarSign,
    PieChart,
    Activity,
    TrendingUp,
    ShieldCheck,
    Download,
    Search
} from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';

const mockFinancialsByProject: Record<string, any> = {
    '1': {
        totalRevenue: 125430,
        platformFees: 6271.50,
        netDistributed: 119158.50,
        payoutHistory: [
            { id: 'tx1', member: 'Sarah Johnson', amount: 15400, role: 'Lead Frontend', date: '2026-06-15', status: 'delivered' },
            { id: 'tx2', member: 'David Kim', amount: 12200, role: 'Full Stack', date: '2026-06-14', status: 'delivered' },
            { id: 'tx3', member: 'Alex Chen', amount: 8500, role: 'UI Designer', date: '2026-06-10', status: 'processing' },
            { id: 'tx4', member: 'Platform (Trust Fee)', amount: 2508.60, role: 'Escrow Fee', date: '2026-06-15', status: 'completed' },
        ],
        milestoneEarnings: [
            { phase: 'Planning & Design', revenue: 15000, date: 'Feb 2026' },
            { phase: 'Development Alpha', revenue: 45000, date: 'Mar 2026' },
            { phase: 'Market Launch', revenue: 65430, date: 'May 2026' },
        ]
    },
    '8': {
        totalRevenue: 0,
        platformFees: 0,
        netDistributed: 0,
        payoutHistory: [],
        milestoneEarnings: [
            { phase: 'Shop Setup', revenue: 0, date: 'Pending' },
            { phase: 'Market Launch', revenue: 0, date: 'Pending' }
        ]
    }
};

export function ProjectFinance() {
    const { id } = useParams<{ id: string }>();
    const navigate = useNavigate();
    const [searchQuery, setSearchQuery] = useState('');

    const projectData = mockFinancialsByProject[id || '8'] || mockFinancialsByProject['1'];


    return (
        <div className="min-h-screen bg-slate-50 font-sans">
            {/* Header */}
            <header className="bg-white border-b border-slate-200 sticky top-0 z-50">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <Button variant="ghost" size="icon" onClick={() => navigate(-1)}>
                            <ArrowLeft className="h-5 w-5" />
                        </Button>
                        <div>
                            <h1 className="text-xl font-bold text-slate-900">Financial Transparency Report</h1>
                            <p className="text-xs text-slate-500 font-medium uppercase tracking-wider">Project ID: {id || '8'} • Real-time Audit</p>
                        </div>
                    </div>
                    <div className="flex items-center gap-3">
                        <Button variant="outline" className="gap-2 text-slate-600 border-slate-200">
                            <Download className="h-4 w-4" />
                            Export Audit Log
                        </Button>
                        <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200 px-3 py-1 font-bold">
                            <ShieldCheck className="h-3 w-3 mr-1" />
                            PLATFORM VERIFIED
                        </Badge>
                    </div>
                </div>
            </header>

            <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
                {/* Stats Grid */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <Card className="bg-slate-900 text-white overflow-hidden relative border-none shadow-xl shadow-slate-900/10">
                        <div className="absolute top-0 right-0 p-6 opacity-10">
                            <DollarSign className="h-24 w-24" />
                        </div>
                        <CardHeader className="pb-2">
                            <CardTitle className="text-sm font-bold text-slate-400 uppercase tracking-widest">Gross Sales (Total Revenue)</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="flex items-baseline gap-2">
                                <span className="text-4xl font-bold">${projectData.totalRevenue.toLocaleString()}</span>
                                <Badge className="bg-green-500 text-white border-none text-[10px]">+12.4%</Badge>
                            </div>
                            <p className="text-xs text-slate-500 mt-2">Cumulative revenue generated by project sales</p>
                        </CardContent>
                    </Card>

                    <Card className="bg-white border-slate-200 shadow-sm">
                        <CardHeader className="pb-2">
                            <CardTitle className="text-sm font-bold text-slate-400 uppercase tracking-widest">Platform & Escrow Fees</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="flex items-baseline gap-2">
                                <span className="text-4xl font-bold text-slate-900">${projectData.platformFees.toLocaleString()}</span>
                                <span className="text-slate-400 text-sm font-medium">5% Fixed Rate</span>
                            </div>
                            <p className="text-xs text-slate-500 mt-2">Fees for contract protection and distribution services</p>
                        </CardContent>
                    </Card>

                    <Card className="bg-white border-slate-200 shadow-sm border-l-4 border-l-primary-500">
                        <CardHeader className="pb-2">
                            <CardTitle className="text-sm font-bold text-slate-400 uppercase tracking-widest">Net Distribution Pool</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="flex items-baseline gap-2">
                                <span className="text-4xl font-bold text-primary-600">${projectData.netDistributed.toLocaleString()}</span>
                            </div>
                            <p className="text-xs text-slate-500 mt-2">Capital available for team member revenue sharing</p>
                        </CardContent>
                    </Card>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                    {/* Distribution History */}
                    <div className="lg:col-span-2 space-y-6">
                        <Card className="border-slate-200 shadow-sm overflow-hidden">
                            <CardHeader className="border-b border-slate-100 bg-white flex flex-row items-center justify-between">
                                <div>
                                    <CardTitle className="text-lg">Detailed Payout History</CardTitle>
                                    <CardDescription>Full log of platform-released funds</CardDescription>
                                </div>
                                <div className="relative w-64">
                                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
                                    <Input
                                        placeholder="Filter by member..."
                                        className="pl-9 h-9 text-sm rounded-lg"
                                        value={searchQuery}
                                        onChange={(e) => setSearchQuery(e.target.value)}
                                    />
                                </div>
                            </CardHeader>
                            <CardContent className="p-0">
                                <div className="divide-y divide-slate-100">
                                    {projectData.payoutHistory.length === 0 ? (
                                        <div className="p-8 text-center text-slate-500 italic text-sm">
                                            No funds have been released for this project yet.
                                        </div>
                                    ) : (
                                        projectData.payoutHistory.map((tx: any) => (
                                            <div key={tx.id} className="p-4 flex items-center justify-between hover:bg-slate-50 transition-colors">
                                                <div className="flex items-center gap-4">
                                                    <div className="h-10 w-10 rounded-full bg-slate-100 flex items-center justify-center font-bold text-slate-500">
                                                        {tx.member[0]}
                                                    </div>
                                                    <div>
                                                        <p className="font-semibold text-slate-900">{tx.member}</p>
                                                        <p className="text-xs text-slate-500">{tx.role} • {tx.date}</p>
                                                    </div>
                                                </div>
                                                <div className="text-right">
                                                    <p className="font-bold text-slate-900">${tx.amount.toLocaleString()}</p>
                                                    <Badge
                                                        variant="outline"
                                                        className={`text-[10px] uppercase font-bold px-1.5 py-0 border-none ${tx.status === 'delivered' ? 'bg-green-50 text-green-700' :
                                                            tx.status === 'processing' ? 'bg-blue-50 text-blue-700' :
                                                                'bg-slate-50 text-slate-500'
                                                            }`}
                                                    >
                                                        {tx.status}
                                                    </Badge>
                                                </div>
                                            </div>
                                        ))
                                    )}
                                </div>
                            </CardContent>
                        </Card>
                    </div>

                    {/* Performance Insights */}
                    <div className="space-y-6">
                        <Card className="border-slate-200 shadow-sm">
                            <CardHeader>
                                <CardTitle className="text-base flex items-center gap-2">
                                    <PieChart className="h-4 w-4 text-primary-500" />
                                    Revenue by Phase
                                </CardTitle>
                            </CardHeader>
                            <CardContent className="space-y-6">
                                {projectData.milestoneEarnings.map((milestone: any, i: number) => (
                                    <div key={i} className="space-y-2">
                                        <div className="flex justify-between text-xs">
                                            <span className="font-semibold text-slate-700">{milestone.phase}</span>
                                            <span className="font-bold text-slate-900">${milestone.revenue.toLocaleString()}</span>
                                        </div>
                                        <div className="h-2 bg-slate-100 rounded-full overflow-hidden">
                                            <div
                                                className="h-full bg-primary-500 rounded-full"
                                                style={{ width: projectData.totalRevenue > 0 ? `${(milestone.revenue / projectData.totalRevenue) * 100}%` : '0%' }}
                                            />
                                        </div>
                                        <p className="text-[10px] text-slate-400">{milestone.date} performance</p>
                                    </div>
                                ))}
                            </CardContent>
                        </Card>

                        <Card className="bg-gradient-to-br from-primary-600 to-indigo-700 text-white border-none overflow-hidden relative hidden lg:block">
                            <div className="absolute top-0 right-0 p-4 opacity-10">
                                <TrendingUp className="h-24 w-24 text-white" />
                            </div>
                            <CardHeader className="pb-2">
                                <CardTitle className="text-base flex items-center gap-2 text-white">
                                    <Activity className="h-4 w-4 text-primary-200" />
                                    Growth Analysis
                                </CardTitle>
                            </CardHeader>
                            <CardContent className="space-y-4 relative z-10 text-white">
                                <p className="text-sm text-primary-50">This project is in the top 5% of revenue-based collaborations this quarter.</p>
                                <div className="p-3 bg-white/10 rounded-lg border border-white/10 flex items-center justify-between">
                                    <span className="text-xs uppercase font-bold tracking-widest text-primary-200">Burn Rate</span>
                                    <p className="text-xl font-bold flex items-center gap-1">
                                        <TrendingUp className="h-4 w-4 text-primary-300" />
                                        {projectData.totalRevenue > 0 ? '+15.2%' : '0%'}
                                    </p>
                                </div>
                                <p className="text-[10px] text-primary-100 uppercase tracking-widest mt-1">Projected Growth</p>
                                <Button className="w-full bg-white text-primary-900 hover:bg-primary-50 font-bold h-10">
                                    Unlock Strategy Report
                                </Button>
                            </CardContent>
                        </Card>
                    </div>
                </div>
            </main>
        </div>
    );
}
